config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'
  devise_for :users

  get "teams/invite", :to => 'teams#invite'
  post "teams/join", :to => 'teams#join'

  resources :lineups

  resources :players, only: [:show]
  resources :leagues, only: [:new, :create, :show] do
    resources :teams, only: [:new, :create, :show, :index, :update] do
      resources :rosters, only: [:new, :create, :show, :index, :update, :destroy]
      resources :players do
        post "/drop", to: 'players#drop', as: :drop
      end
    end
    resources :drafts, only: [:index, :show, :new, :create] do
      resources :picks
    end
    resources :players, only: [:index, :update]
  end

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :users, through: :teams
  has_many :teams
  has_many :drafts

  validates :name, presence: true
  validates :member_amount, presence: true

  def has_drafted?
    if self.drafts.empty?
      return false
    else
      self.drafts.each do |draft|
        if draft.created_at.year == Time.now.year && draft.picks.count == (self.member_amount.to_i * self.max_players)
          return true
        end
      end
    end
    false
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    @league.commissioner_id = current_user.id
    if @league.save
      flash[:notice] = "League created. Now add your team:"
      redirect_to new_league_team_path(@league)
    else
      @errors = @league.errors.full_messages
      render :new
    end
  end

  def index
    @teams = current_user.teams
  end

  def show
    @league = League.find(params[:id])
    @teams = @league.teams
    @team = current_user.teams.where(league_id: @league.id).first
  end

  private

  def league_params
    params.require(:league).permit(:name, :password, :member_amount)
  end
end

app/views/leagues/index.html.erb
<div class="user-home-container">
<div class="user-home-title">
My Teams and Leagues:
</div>
<% if @teams.empty? %>
You are not in any leagues. <%= link_to "Create a League Now", new_league_path %> and invite your friends!
<% end %>
<% @teams.each do |team| %>
<div class="user-home-row">
<%= link_to team.name, league_team_path(team.league, team), :class => "user-home-row-team-name" %>
<div class="user-home-row-team-record">
<%= "(#{team.wins} - #{team.losses} - #{team.ties}) | #{team.standing}" %>
</div>
<%= link_to team.league.name, league_path(team.league), :class => "user-home-row-team-league" %>
</div>
<% end %>
</div>
<div class="user-home-row-buttons-container">
<%= link_to "Join a League", teams_invite_path, :class => "index-join-league" %>
<%= link_to "Create a League", new_league_path, :class => "index-join-league" %>
</div>

app/views/leagues/new.html.erb
<div class="login-form-container">
<div class="login-title">Create a New League</div>
<%= @errors %>
<%= form_for @league do |f| %>
  <div class="login-email-container">
<%= f.label :name, :class => "login-email"  %>
<%= f.text_field :name, :class => "login-email-field" %>
    </div>
    <div class="login-email-container">
<%= f.label :password, :class => "login-password" %>
<%= f.text_field :password, :class => "login-email-field" %>
</div>
<%= f.select(:member_amount, %w[8 10 12 14 16 18 20], {prompt: "Member Amount"}, :class => "form-dropdown") %>
<%= f.submit "Create League", :class => "login-submit" %>
<% end %>

app/views/leagues/show.html.erb
<div class="league-name">
<%= @league.name %>
</div>
<div class="league-navbar">
<%= link_to "League Home", league_path(@league), class: "league-navbar-element" %>
<%= link_to "My Team", league_team_path(@league, @team), class: "league-navbar-element" %>
<%= link_to "Free Agents", league_players_path(@league), class: "league-navbar-element" %>
<a href="#" class="league-navbar-element">Schedule</a>
<a href="#" class="league-navbar-element">League Settings</a>
<a href="#" class="league-navbar-element">Team Settings</a>
</div>
<% if current_user.has_team_in(@league) == false %>
<form class="league-add-team" method="get" action="/leagues/<%= @league.id %>/teams/new">
<label style="margin: 0;padding: 0;">
<svg class="svg-icon" viewBox="0 0 20 20">
<path fill="none" d="M13.388,9.624h-3.011v-3.01c0-0.208-0.168-0.377-0.376-0.377S9.624,6.405,9.624,6.613v3.01H6.613c-0.208,0-0.376,0.168-0.376,0.376s0.168,0.376,0.376,0.376h3.011v3.01c0,0.208,0.168,0.378,0.376,0.378s0.376-0.17,0.376-0.378v-3.01h3.011c0.207,0,0.377-0.168,0.377-0.376S13.595,9.624,13.388,9.624z M10,1.344c-4.781,0-8.656,3.875-8.656,8.656c0,4.781,3.875,8.656,8.656,8.656c4.781,0,8.656-3.875,8.656-8.656C18.656,5.219,14.781,1.344,10,1.344z M10,17.903c-4.365,0-7.904-3.538-7.904-7.903S5.635,2.096,10,2.096S17.903,5.635,17.903,10S14.365,17.903,10,17.903z">
</path>
</svg>
<input id="4" class="league-add-team-button" type="submit" value="Add Team">
</label>
</form>
<% end %>
<%= render partial: "teams/index", locals: { league: @league } %>

<% if (@teams.count == @league.member_amount.to_i) && !@league.has_drafted? %>
<div class="start-draft-container">
<div class="start-draft-minimize-button">
-
</div>
Your league is ready to draft.
<%= link_to "Start Draft", new_league_draft_path(@league), :class => "start-draft-button" %>
</div>
<% end %>

<a href="<%= @league.id %>/drafts/new" class="start-draft-button-minimized">
<img src="/draft-icon.png" style="height: 30px; margin-right: 24px;">
Start Draft
</a>