config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'
  devise_for :users

  get "teams/invite", :to => 'teams#invite'
  post "teams/join", :to => 'teams#join'

  resources :lineups

  resources :players, only: [:show]
  resources :leagues, only: [:new, :create, :show] do
    resources :teams, only: [:new, :create, :show, :index, :update] do
      resources :rosters, only: [:new, :create, :show, :index, :update, :destroy]
      resources :players do
        post "/drop", to: 'players#drop', as: :drop
      end
    end
    resources :drafts, only: [:index, :show, :new, :create] do
      resources :picks
    end
    resources :players, only: [:index, :update]
  end

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  has_many :rounds
  has_many :teams
  has_many :players
  belongs_to :league
  has_many :picks, through: :rounds

  validates :league_id, presence: true

  def autorun
    picks = self.league.teams.count * self.league.max_players
    round_reset = self.league.teams.count - 1
    pick_number = 1
    round_number = 1
    round = Round.create(number: round_number, draft_id: self.id)
    players = Player.where(position: "QB")
    i = 0
    teams = self.league.teams
    until picks == 0
      if round_reset == -1
        round_number += 1
        pick_number = 1
        round = Round.create(number: round_number, draft_id: self.id )
        round_reset = self.league.teams.count - 1
      end
      if round.number > 9
        players = Player.where(position: "RB")
      elsif round.number > 4
        players = Player.where(position: "WR")
      elsif round.number > 2
        players = Player.where(position: "TE")
      end
      pick = round.picks.new(
        number: pick_number,
        price: 5,
        round_id: self.id,
        player_id: players[i].id,
        team_id: teams[round_reset].id
        )
      team_roster = teams[round_reset].rosters.new(
      player_id: pick.player_id,
      status: "member")
      if round.number == 1
        team_roster.position = "QB"
      elsif round.number == 3
        team_roster.position = "TE"
      elsif round.number == 5
        team_roster.position = "WR1"
      elsif round.number == 6
        team_roster.position = "WR2"
      elsif round.number == 10
        team_roster.position = "RB1"
      elsif round.number == 11
        team_roster.position = "RB2"
      elsif round.number == 12
        team_roster.position = "FLEX"
      else
        team_roster.position = "BN"
      end
      if pick.save && team_roster.save
        puts "Round #{round.number} | Pick #{pick.number} : #{Player.find(pick.player_id).first_name} #{Player.find(pick.player_id).last_name} - #{Team.find(pick.team_id).name}"
      end
      i += 1
      round_reset -= 1
      picks -=1
      pick_number += 1
    end
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :authenticate, :commissioner_authenticate
  def index
    binding.pry
  end
  def show
    binding.pry
    @pick = Pick.new
  end
  def new
    @league = League.find(params[:league_id])
    if @league.teams.count < @league.member_amount.to_i
      flash[:notice] = "Your league is not full yet and cannot draft"
      redirect_to league_path(@league)
    else
      @draft = Draft.new
      render :new, layout: false
    end
  end
  def create
    @league = League.find(params[:league_id])
    member_amount = @league.teams.count
    @teams = []
    until member_amount == 0
      @teams << Team.find(params["team_id-#{member_amount}"])
      member_amount -= 1
    end
    @teams.reverse!
    @players = Player.all
    @draft = Draft.new(league_id: @league.id)
    if @draft.save
      @pick = Pick.new(number: 1)
      @round = Round.new(number: 1, draft_id: @draft.id)
      @round.save
      @team_lineups = {}
      @teams.each do |team|
        @team_lineups[team.id] = team.project_lineup
      end
      render :show, layout: false
    else
      flash[:notice] = "Something went wrong. Leave feedback or try again later."
      redirect_to league_path(@league)
    end
  end
end

app/views/drafts/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Fooball</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <script>
  $(function() {
    $( "#sortable" ).sortable({
      revert: true
    });
    $( "#draggable" ).draggable({
      connectToSortable: "#sortable",
      helper: "clone",
      revert: "invalid"
    });
    $( "ul, li" ).disableSelection();
  });
  </script>
</head>

<body>
<div class="draft-header-new">
<%= "#{Time.now.year} #{@league.name} Draft" %>
</div>
<div class="draft-order-container">
<%= form_for @draft, method: :post, action: :create, url: league_drafts_path(@league) do |f| %>
  Set draft order:
  <ol id="sortable">
  <% i = 1 %>
  <% @league.teams.each do |team| %>
  <li class="sortable-list-element">
  <%= team.name %>
  <%= hidden_field_tag "team_id-#{i}", "#{team.id}" %>
  <% i += 1 %>
  </li>
  <% end %>
  </ol>
  <%= f.submit "Submit", :class => "login-submit" %>
<% end %>
</div>
</body>

app/views/drafts/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Fooball</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <style>
  h1 { padding: .2em; margin: 0; }
  #products { float:left; width: 500px; margin-right: 2em; }
  #cart { width: 200px; float: left; margin-top: 1em; }
  /* style the list to maximize the droppable hitarea */
  #cart ol { margin: 0; padding: 1em 0 1em 3em; }
  </style>
  <script>
  $(function() {
    $( "#catalog" ).accordion();
    $( ".player-name" ).draggable({
      appendTo: "body",
      helper: "clone"
    });
    $( "#nomination" ).droppable({
      activeClass: "#nomination",
      hoverClass: "#nomination",
      accept: ":not(.ui-sortable-helper)",
      drop: function( event, ui ) {
        $( this ).find( ".placeholder" ).remove();
        $( "<div></div>" ).text( ui.draggable.text() ).addClass("nominated-player").appendTo( this );
        $( this ).addClass( "bid" );
        $( this ).removeAttr('id');
        $( ".new_pick" ).css("display", "flex");
        var hiddenInput = $(".hidden-player-id", ui.draggable);
        $(".price-input").append(hiddenInput);
      }
    }).sortable({
      items: "li:not(.placeholder)",
      sort: function() {
        // gets added unintentionally by droppable interacting with sortable
        // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
        $( this ).removeClass( "ui-state-default" );
      }
    });
  });
  $(function() {
    $( "#draft-dropdown-teams-placeholder" ).hover(
      function() {
        $( this ).css("display", "none");
        $( ".new_pick-team" ).css("display", "block");
      }
    );
  });
  $(function() {
    $( ".new_pick-team" ).click(
      function() {
        var selectedTeam = $( "form option[value=" + $(this).val() + "]").text()
        $( ".new_pick-team" ).css("display", "none");
        $( "#draft-dropdown-teams-placeholder" ).css("display", "block").text(selectedTeam);
      })
  })
  $(function() {
    $( ".draft-header-teams" ).mouseenter(
      function() {
        var value = $(this).attr("value");
        $(".draft-header-teams-dropdown[value=" + value + "]").css("display", "flex");
      })
  })
  $(function() {
    $( ".draft-header-teams" ).mouseout(
      function() {
        var value = $(this).attr("value");
        $(".draft-header-teams-dropdown[value=" + value + "]").css("display", "none");
      })
  })
  </script>
</head>

<body>
  <div class="draft-header">
  <div class="draft-header-title">
    <%= "#{Time.now.year} #{@league.name} Draft" %>
  </div>

  <% i = 1 %>
  <% @teams.each do |team| %>
  <div class="draft-team-container">
  <div class="draft-header-teams" value="<%= team.id %>">
  <div class="draft-header-teams-position">
  <%= i %>
  </div>
  <div class="draft-header-teams-name">
  <%= team.name %>
  </div>
  </div>
  <% i += 1 %>

<div class="draft-header-teams-dropdown" value="<%= team.id %>">
  <% team.project_lineup.each do |position, player| %>
    <div class="draft-header-teams-row">
      <div class="draft-header-teams-position">
      <%= position.to_s %>
      </div>
      <div class="draft-header-teams-player-name">
      <% if player.is_a?(String) %>
      <%= player %>
      <% else %>
      <%= "#{player.first_name} #{player.last_name}" %>
      <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

  <% end %>
  </div>

  <div class="draft-container">
    <div class="player-list">
      <div class="player-row-header">
        <div class="player-position-header">
        Pos:
        </div>
        <div class="player-name-header">
        Player Name
        </div>
        <div class="player-age-header">
        Age
        </div>
      </div>
      <div class="player-list-content">
        <% @players.each do |player| %>
          <% if !player.position.nil? %>
            <div class="player-row">
              <div class="player-position">
                <%= player.position %>
              </div>
              <div class="player-name">
                <%= "#{player.first_name} #{player.last_name}"%>
                <input type="hidden" class="hidden-player-id" name="player_id" value="<%= player.id %>">
              </div>
              <div class="player-age">
                <%= player.age %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div id="nomination">
      N O M I N A T E
    </div>
    <%= form_for [@league, @draft, @pick] do |f| %>
    <input type="hidden" class="hidden-player-id" name="player_id">
    <%= f.label :price, "Price: $", :class => "price-label" %>
    <%= f.text_field :price, :class => "price-input" %>
    <%= hidden_field_tag "round_id", "#{@round.id}" %>
    <%= f.label :team_id, "Drafted By:" %>
    <div class="draft-dropdown-teams">
    <div id="draft-dropdown-teams-placeholder">
    Pick a Team
    </div>
    <%= f.select :team_id, @teams.collect {|x| [x.name, x.id]}, {}, :multiple => true, :class => "new_pick-team" %>
    </div>
    <%= hidden_field_tag "pick[number]", "#{@pick.number}" %>
    <% i = 0 %>
    <% @teams.each do |team| %>
      <%= hidden_field_tag "team_order[#{i}]", "#{team.id}" %>
      <% i += 1 %>
    <% end %>
    <%= f.submit "Sold", :class => "price-submit" %>
    <% end %>

    <div id="draft-queue">
    <div id="draft-queue-title">
    Queue Nominations:
    </div>
    <ol id="draft-queue-drop">
      <li class="placeholder">
        (Drag and drop here)
      </li>
    </ol>
    </div>
  </div>
</body>